apiVersion: apps/v1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: hellodeployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hellodeployment
  template:
    metadata:
      labels:
        app: hellodeployment
    spec:
      containers:
      - name: hellostarlingx
        image: registry.local:9001/windse/starlingx-nodeinfo:v1.0-v6
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
      imagePullSecrets:
      - name: admin-registry-secret

