apiVersion: v1
kind: Service
metadata:
  name: nodeport
  labels:
    app: hellodeployment
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30001
  selector:
    app: hellodeployment
